services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chess_db
    ports:
     - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "chess_db", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app-server:
    build: ./server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./server
        target: /root
    command: "uvicorn src.main:app --port=8000 --host=0.0.0.0 --reload"

  app-client:
    build: ./client
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./client
        target: /root
    command: "npm run dev"

volumes:
  postgres_data:
