services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chess_db
    ports:
     - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "chess_db", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5



  app:
    image: domnuraul/chess-app:0.9
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - .:/root
    command: "uvicorn src.main:app --port=8000 --host=0.0.0.0"



volumes:
  postgres_data:
